### ISSUE TITLE
Probably not public information

### ISSUE THREAD

**Issue by low-sky** [itoledoc/gWTO2#1]
Hi there!  The aprcflags on Cycle 2 proposals probably aren't public knowledge.  I found out that a proposal we are reviewing is filler based on google finding [this file](https://github.com/itoledoc/gWTO2/blob/master/conf/c2grade.csv).

**Comment by itoledoc** [comment]
Thanks Erik! I'll set the project to private, as I thought I did in the
past.

Cheers
I.

**Comment by itoledoc** [comment]
File Removed.
